### PR TITLE
fix(security): update vulnerabilities

### PR DESCRIPTION
**Pull request by sicoyle**
# Description

Related to efforts to improve security vulnerabilities. Other efforts below that are related:
https://github.com/dapr/dapr/pull/7681
https://github.com/dapr/components-contrib/pull/3390

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests

### CODE REVIEW

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
LGTM but the snyk scanners are reporting errors. Looks like I don't have access to them, can someone check them please?
image

**Comment by artursouza** [comment]
image

**Comment by sicoyle** [comment]
looks like it was just flaky? cc @artursouza @ItalyPaleAle bc it passed that last time 🙌

**Comment by artursouza** [comment]
image

**Comment by sicoyle** [comment]
ready for merge pls @ItalyPaleAle @artursouza

**Review by ItalyPaleAle — APPROVED** [review]

**Comment by ItalyPaleAle** [comment]
@artursouza please grant @yaron2 , myself, and the other maintainers access to the Snyk dashboard

**Pull request merged**
